// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:xvibe_offline_mp3_player/models/song.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SongAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SongAdapter());
  }
}
